[2025-08-18 22:10:35,385: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-08-18 22:10:35,401: INFO/MainProcess] mingle: searching for neighbors
[2025-08-18 22:10:36,515: INFO/MainProcess] mingle: all alone
[2025-08-18 22:10:36,708: INFO/MainProcess] celery@APC-AP-13RQPB4 ready.
[2025-08-18 23:19:17,857: ERROR/MainProcess] Received unregistered task of type 'core.utils.celery_worker.pooling_mail_box'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["01K2Z4S3SV806Z3VN4EH2MXDZ6", "SECONDLY30"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (119b)

The full contents of the message headers:
{'lang': 'py', 'task': 'core.utils.celery_worker.pooling_mail_box', 'id': '01K2Z4SFYR2Z1FCCWJAP28MGPV', 'shadow': None, 'eta': '2025-08-18T17:49:22.659686', 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '01K2Z4SFYR2Z1FCCWJAP28MGPV', 'parent_id': None, 'argsrepr': "['01K2Z4S3SV806Z3VN4EH2MXDZ6', 'SECONDLY30']", 'kwargsrepr': '{}', 'origin': 'gen26688@APC-AP-13RQPB4', 'ignore_result': True, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'main-queue'}
Traceback (most recent call last):
  File "c:\Users\JigarVaishnav\Projects\pv-tool-be\.venv\Lib\site-packages\celery\worker\consumer\consumer.py", line 662, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'core.utils.celery_worker.pooling_mail_box'
[2025-08-18 23:27:39,014: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-08-18 23:27:39,028: INFO/MainProcess] mingle: searching for neighbors
[2025-08-18 23:27:40,098: INFO/MainProcess] mingle: all alone
[2025-08-18 23:27:40,182: INFO/MainProcess] celery@APC-AP-13RQPB4 ready.
[2025-08-18 23:30:39,344: ERROR/MainProcess] Received unregistered task of type 'core.utils.celery_worker.pooling_mail_box'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["01K2Z5DV6G4FFF5D9FJT3G96EP", "SECONDLY30"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (119b)

The full contents of the message headers:
{'lang': 'py', 'task': 'core.utils.celery_worker.pooling_mail_box', 'id': '01K2Z5E10EB0PEDB0874WSV8AV', 'shadow': None, 'eta': '2025-08-18T18:00:37.342776', 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '01K2Z5E10EB0PEDB0874WSV8AV', 'parent_id': None, 'argsrepr': "['01K2Z5DV6G4FFF5D9FJT3G96EP', 'SECONDLY30']", 'kwargsrepr': '{}', 'origin': 'gen28716@APC-AP-13RQPB4', 'ignore_result': True, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'main-queue'}
Traceback (most recent call last):
  File "c:\Users\JigarVaishnav\Projects\pv-tool-be\.venv\Lib\site-packages\celery\worker\consumer\consumer.py", line 662, in on_task_received
    strategy = strategies[type_]
               ~~~~~~~~~~^^^^^^^
KeyError: 'core.utils.celery_worker.pooling_mail_box'
